name: Build and deploy .NET Core application to Web App Fashion-Shop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: Fashion-Shop
  AZURE_WEBAPP_PACKAGE_PATH: API\publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  SOLUTION_FILE: FashionShopManagement.sln  # Tên solution file

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Ensure NuGet Config is Correct
      run: |
        dotnet nuget locals all --clear
        dotnet restore "${{ env.SOLUTION_FILE }}" --force

    - name: Debug Missing Packages
      run: dotnet list "${{ env.SOLUTION_FILE }}" package

    - name: Build Entire Solution
      run: dotnet build "${{ env.SOLUTION_FILE }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Run Unit Tests
      run: dotnet test "${{ env.SOLUTION_FILE }}" --no-build || echo "Skipping tests"

    - name: Publish Web API
      run: dotnet publish "API/API.csproj" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.Fashion_Shop_FD1B }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
